#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/zeroclaw
CONFIG_DIR=/root/.zeroclaw

start_service() {
    procd_open_instance zeroclaw
    procd_set_param command $PROG daemon --config-dir $CONFIG_DIR
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param env SHELL=/bin/ash HOME=/root PATH=/usr/sbin:/usr/bin:/sbin:/bin
    procd_set_param pidfile /var/run/zeroclaw.pid
    procd_close_instance
}

stop_service() {
    killall zeroclaw 2>/dev/null
}
